### ISSUE TITLE
Handling "colorized" code blocks

### ISSUE THREAD

**Issue by ttscoff** [ylian/unmarked#1]
I haven't dug into the code much yet, but I think it would be a worthwhile feature (or option) to be able to automatically strip markup tags from colorized code blocks. It seems to work fine in a plan `pre>code` situation, but a code block such as found on [this post](http://brettterpstra.com/2015/11/16/shell-tricks-convert-file-urls-to-unix-paths/) causes the contents to be escaped and newlines stripped.

In the case above, it would just mean exploding the span tags, but there are a lot of highlighting systems that create tables and other crap. I'd be fine with ignoring those.

Given its use in Quiver, this seems like it would be useful, no?

**Comment by ylian** [comment]
Thanks, Brett. This library can only handle basic cases right now. It's only a starting point.
I will add a web clipper to Quiver, and scraping code blocks is in my plan. It probably will involve two libraries: unmarked and [declutter](https://github.com/ylian/declutter). Both libraries are still in their early form.

**Comment by ttscoff** [comment]
Nice, I hadn't noticed declutter. I've hacked around with this issue in 
PHP on markdownrules.com, but it's gotten messy (as PHP has a tendency 
to do). I look forward to developments on this (and Quiver)!

**Comment by ylian** [comment]
I will check your work. Just a heads up, declutter is quite incomplete at the moment, and doesn't work on all pages. But it's a good start. I still have a lot of work to do in both libraries.
